# Generated by Django 4.2.2 on 2023-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
