# Generated by Django 4.2.2 on 2023-07-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade', '0003_alter_hscode_id_alter_region_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='regions',
            new_name='region',
        ),
    ]
